import type { Metadata } from "next"
import { Fredoka } from "next/font/google"
import "./globals.css"
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/layout/app-sidebar"
import { createClient } from "@/lib/supabase/server"

const fredoka = Fredoka({
    variable: "--font-fredoka",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Vaksetu",
    description: "Generated by create next app",
}

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode
}>) {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    const userProfile = user
        ? {
            name: user.user_metadata?.full_name || user.user_metadata?.name || "",
            email: user.email || "",
            avatar: user.user_metadata?.avatar_url || "",
        }
        : null

    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${fredoka.variable} antialiased`}
            style={{ fontFamily: "var(--font-fredoka), sans-serif" }}
            suppressHydrationWarning
        >
        <SidebarProvider defaultOpen={false}>
            <AppSidebar user={userProfile} />
            <SidebarInset>{children}</SidebarInset>
        </SidebarProvider>
        </body>
        </html>
    )
}
